# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pourmanon.ui'
#
# Created: Wed Dec 21 17:27:03 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName("Configuration")
        Configuration.setEnabled(True)
        Configuration.resize(1280, 800)
        self.centralwidget = QtWidgets.QWidget(Configuration)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_Colors_Start = QtWidgets.QLabel(self.centralwidget)
        self.Label_Colors_Start.setGeometry(QtCore.QRect(390, 100, 67, 16))
        self.Label_Colors_Start.setText("")
        self.Label_Colors_Start.setObjectName("Label_Colors_Start")
        self.comboBox_Forms_Start = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Forms_Start.setGeometry(QtCore.QRect(650, 90, 115, 26))
        self.comboBox_Forms_Start.setObjectName("comboBox_Forms_Start")
        self.comboBox_Forms_Start.addItem("")
        self.comboBox_Forms_Start.addItem("")
        self.comboBox_Forms_Start.addItem("")
        self.Colors_Label = QtWidgets.QLabel(self.centralwidget)
        self.Colors_Label.setGeometry(QtCore.QRect(540, 60, 51, 19))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Colors_Label.setFont(font)
        self.Colors_Label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Colors_Label.setObjectName("Colors_Label")
        self.ComboBox_Colors_Start = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_Colors_Start.setGeometry(QtCore.QRect(520, 100, 91, 26))
        self.ComboBox_Colors_Start.setAutoFillBackground(False)
        self.ComboBox_Colors_Start.setObjectName("ComboBox_Colors_Start")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.ComboBox_Colors_Start.addItem("")
        self.Forms_Label = QtWidgets.QLabel(self.centralwidget)
        self.Forms_Label.setGeometry(QtCore.QRect(680, 60, 49, 19))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Forms_Label.setFont(font)
        self.Forms_Label.setObjectName("Forms_Label")
        Configuration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Configuration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        self.menuConfiguration = QtWidgets.QMenu(self.menubar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        Configuration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Configuration)
        self.statusbar.setObjectName("statusbar")
        Configuration.setStatusBar(self.statusbar)
        self.menuConfiguration.addSeparator()
        self.menubar.addAction(self.menuConfiguration.menuAction())

        self.retranslateUi(Configuration)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        _translate = QtCore.QCoreApplication.translate
        Configuration.setWindowTitle(_translate("Configuration", "MainWindow"))
        self.comboBox_Forms_Start.setItemText(0, _translate("Configuration", "Ellipse"))
        self.comboBox_Forms_Start.setItemText(1, _translate("Configuration", "Circle"))
        self.comboBox_Forms_Start.setItemText(2, _translate("Configuration", "Rectangle"))
        self.Colors_Label.setText(_translate("Configuration", "Colors"))
        self.ComboBox_Colors_Start.setItemText(0, _translate("Configuration", "orange"))
        self.ComboBox_Colors_Start.setItemText(1, _translate("Configuration", "red"))
        self.ComboBox_Colors_Start.setItemText(2, _translate("Configuration", "blue"))
        self.ComboBox_Colors_Start.setItemText(3, _translate("Configuration", "green"))
        self.ComboBox_Colors_Start.setItemText(4, _translate("Configuration", "magenta"))
        self.ComboBox_Colors_Start.setItemText(5, _translate("Configuration", "cyan"))
        self.ComboBox_Colors_Start.setItemText(6, _translate("Configuration", "lime"))
        self.ComboBox_Colors_Start.setItemText(7, _translate("Configuration", "purple"))
        self.ComboBox_Colors_Start.setItemText(8, _translate("Configuration", "silver"))
        self.ComboBox_Colors_Start.setItemText(9, _translate("Configuration", "indigo"))
        self.ComboBox_Colors_Start.setItemText(10, _translate("Configuration", "maroon"))
        self.ComboBox_Colors_Start.setItemText(11, _translate("Configuration", "olive"))
        self.ComboBox_Colors_Start.setItemText(12, _translate("Configuration", "navy"))
        self.ComboBox_Colors_Start.setItemText(13, _translate("Configuration", "goldenrhod"))
        self.ComboBox_Colors_Start.setItemText(14, _translate("Configuration", "teal"))
        self.ComboBox_Colors_Start.setItemText(15, _translate("Configuration", "darkorange"))
        self.ComboBox_Colors_Start.setItemText(16, _translate("Configuration", "crimson"))
        self.ComboBox_Colors_Start.setItemText(17, _translate("Configuration", "seagreen"))
        self.ComboBox_Colors_Start.setItemText(18, _translate("Configuration", "steelblue"))
        self.ComboBox_Colors_Start.setItemText(19, _translate("Configuration", "lightcoral"))
        self.ComboBox_Colors_Start.setItemText(20, _translate("Configuration", "grey"))
        self.ComboBox_Colors_Start.setItemText(21, _translate("Configuration", "black"))
        self.ComboBox_Colors_Start.setItemText(22, _translate("Configuration", "orangered"))
        self.Forms_Label.setText(_translate("Configuration", "Forms"))
        self.menuConfiguration.setTitle(_translate("Configuration", "Configuration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Configuration = QtWidgets.QMainWindow()
    ui = Ui_Configuration()
    ui.setupUi(Configuration)
    Configuration.show()
    sys.exit(app.exec_())

